GET http://localhost:8080/books/helloBook

###

GET http://localhost:8080/books

###

GET http://localhost:8080/books/3

###

POST http://localhost:8080/books
Content-Type: application/json

{
  "isbn":"9999999",
  "title":"adsgas",
  "author":"McGavren",
  "publisher":"Helion",
  "type":"programming"
}

###

DELETE http://localhost:8080/books/4

###

PUT http://localhost:8080/books
Content-Type: application/json

{
  "id": 3,
  "isbn":"9999999",
  "title":"adsgas",
  "author":"McGavren",
  "publisher":"Helion",
  "type":"programming"
}
